/**
 * Document Export Utilities
 * 
 * This file provides functionality for exporting documents in various formats,
 * print features, and enhanced PDF generation.
 */

/**
 * Generate a PDF from content and optionally return a URL to the PDF
 * @param content The content to convert to PDF
 * @param filename The filename to use for the PDF
 * @param openPrintDialog Whether to open the print dialog
 * @returns Boolean success or a string URL to the generated PDF data
 */
export const generatePDF = async (
  content: string, 
  filename: string = 'document.pdf', 
  openPrintDialog: boolean = true
): Promise<string> => {
  try {
    // Create a hidden iframe to use for PDF generation
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);
    
    // Extract document title from content or use filename
    let documentTitle = filename.replace(/\.[^/.]+$/, ""); // Remove extension
    
    // Try to extract title from content if it's markdown
    if (content.startsWith('#')) {
      const titleMatch = content.match(/^#\s+(.+)$/m);
      if (titleMatch && titleMatch[1]) {
        documentTitle = titleMatch[1].trim();
      }
    }
    
    // Get current date for the document header
    const formattedDate = new Date().toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    
    // Format content with proper styling and document structure
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${documentTitle}</title>
          <style>
            @page {
              size: A4;
              margin: 2cm;
            }
            body {
              font-family: "Times New Roman", Times, serif;
              font-size: 12pt;
              line-height: 1.5;
              color: black;
              margin: 0;
              padding: 0;
            }
            pre {
              white-space: pre-wrap;
              word-wrap: break-word;
              font-family: "Courier New", monospace;
              margin: 0;
              padding: 0;
            }
            .document-header {
              margin-bottom: 2cm;
            }
            .document-title {
              font-size: 18pt;
              font-weight: bold;
              margin-bottom: 0.5cm;
              text-align: center;
            }
            .document-date {
              font-size: 11pt;
              text-align: center;
              margin-bottom: 0.5cm;
              color: #555;
            }
            .page-break {
              page-break-after: always;
            }
            .watermark {
              position: fixed;
              bottom: 1cm;
              right: 1cm;
              font-size: 9pt;
              color: #999;
              opacity: 0.7;
            }
            
            /* Print-specific styles */
            @media print {
              body {
                padding: 0;
              }
            }
          </style>
        </head>
        <body>
          <div class="document-header">
            <div class="document-title">${documentTitle}</div>
            <div class="document-date">${formattedDate}</div>
          </div>
          <div class="document-content">
            <pre>${content}</pre>
          </div>
          <div class="watermark">Generated by Canadian Legal AI</div>
        </body>
      </html>
    `;
    
    // Write content to iframe
    if (iframe.contentWindow) {
      iframe.contentWindow.document.open();
      iframe.contentWindow.document.write(html);
      iframe.contentWindow.document.close();
    } else {
      console.error("Could not access iframe content window");
      document.body.removeChild(iframe);
      throw new Error('Failed to initialize document preview');
    }
    
    return new Promise<boolean | string>((resolve) => {
      // Set a timeout to ensure the iframe has loaded
      setTimeout(() => {
        try {
          const win = iframe.contentWindow;
          
          if (!win) {
            throw new Error('Failed to access content window');
          }
          
          // If we need to open print dialog
          if (openPrintDialog) {
            // Check browser capabilities
            if (navigator.userAgent.indexOf('Chrome') > -1 || 
                navigator.userAgent.indexOf('Firefox') > -1 || 
                navigator.userAgent.indexOf('Safari') > -1) {
              // These browsers have better PDF export support
              win.focus();
              win.print();
              resolve(true);
            } else {
              // For other browsers, provide text fallback
              exportAsText(content, filename.replace(/\.pdf$/i, '.txt'));
              resolve(false);
            }
          } else {
            // Create a simple data URL with the HTML content
            const blob = new Blob([html], { type: 'text/html' });
            const url = URL.createObjectURL(blob);
            
            // Ensure to clean up the iframe
            setTimeout(() => {
              try {
                document.body.removeChild(iframe);
              } catch (e) {
                console.warn('Iframe already removed', e);
              }
            }, 500);
            
            resolve(url);
          }
        } catch (err) {
          console.error('Error in PDF generation process:', err);
          try {
            document.body.removeChild(iframe);
          } catch (e) {
            console.warn('Iframe already removed', e);
          }
          
          // Fallback to text for preview
          const blob = new Blob([content], { type: 'text/plain' });
          const url = URL.createObjectURL(blob);
          resolve(url);
        }
      }, 300); // Short delay to ensure content is loaded
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return false;
  }
};

/**
 * Export document as plain text
 * @param content The content to export
 * @param filename The filename to use for the text file
 */
export const exportAsText = async (content: string, filename: string = 'document.txt') => {
  try {
    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = filename;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    return true;
  } catch (error) {
    console.error('Error exporting as text:', error);
    throw new Error('Failed to export as text. Please try again.');
  }
};

/**
 * Print document to local printer
 * @param content The content to print
 * @param title The title of the document
 */
export const printDocument = (content: string, title: string = 'Document') => {
  try {
    // Format date for document header
    const formattedDate = new Date().toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    
    // Create a hidden iframe for printing
    const iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    document.body.appendChild(iframe);
    
    // Add document title and date to content
    const contentWithHeader = `${title}\n\n${formattedDate}\n\n${content}`;
    
    // Write content to iframe
    iframe.contentDocument?.open();
    
    // Add necessary styling for print
    iframe.contentDocument?.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title}</title>
          <style>
            body {
              font-family: "Times New Roman", Times, serif;
              line-height: 1.5;
              margin: 0;
              padding: 0;
              color: black;
            }
            
            .document-header {
              text-align: center;
              margin-bottom: 1.5cm;
            }
            
            .document-title {
              font-size: 18pt;
              font-weight: bold;
              margin-bottom: 0.5cm;
            }
            
            .document-date {
              font-size: 12pt;
              margin-bottom: 1cm;
            }
            
            .document-content {
              font-size: 12pt;
            }
            
            pre {
              white-space: pre-wrap;
              word-wrap: break-word;
              font-family: "Courier New", monospace;
              font-size: 12pt;
              margin: 0;
            }
            
            @media print {
              @page {
                size: A4;
                margin: 2cm;
              }
              
              body {
                padding: 0;
              }
              
              .page-break {
                page-break-after: always;
              }
            }
          </style>
        </head>
        <body>
          <div class="document-header">
            <div class="document-title">${title}</div>
            <div class="document-date">${formattedDate}</div>
          </div>
          <div class="document-content">
            <pre>${content}</pre>
          </div>
        </body>
      </html>
    `);
    
    iframe.contentDocument?.close();
    
    // Wait for content to load before printing
    iframe.onload = () => {
      try {
        iframe.contentWindow?.focus();
        iframe.contentWindow?.print();
        
        // Remove iframe after printing (or if print dialog is closed)
        setTimeout(() => {
          document.body.removeChild(iframe);
        }, 1000);
      } catch (err) {
        console.error('Error during print process:', err);
        document.body.removeChild(iframe);
      }
    };
    
    return true;
  } catch (error) {
    console.error('Error initializing print process:', error);
    throw new Error('Failed to print document. Please try again.');
  }
};

/**
 * Detect browser print capabilities
 */
export const checkPrintCapabilities = () => {
  return {
    canPrint: typeof window !== 'undefined' && 'print' in window,
    hasPrintDialog: typeof window !== 'undefined' && 
                    navigator.userAgent.toLowerCase().indexOf('chrome') > -1,
    supportsPdfExport: false // Will update when jsPDF is implemented
  };
};

/**
 * Format document based on desired format before export
 * @param content The raw document content
 * @param format The desired format
 */
export const formatDocumentForExport = (content: string, format: 'pdf' | 'txt' = 'txt') => {
  // For simple text format, just return as is
  if (format === 'txt') {
    return content;
  }
  
  // For PDF, we might need to format differently, but for now return as is
  return content;
};